---
dns_adblock_lists_extras: []
dns_adblock_lists: "{{ dns_lists_defaults + dns_lists_extras }}"

# Often blocklists contain these IPs. We want to remove them from our lists
dns_replace_address:
  - '([0]{1,3}\.){3}[0]{1,3} '  # Beware of the necessary trailing whitespace!
  - 'localhost '                     # It is there to not match records like 1.2.3.4.domain.tld
  - '::1'
